# Generated by Django 6.0.6 on 2026-06-14 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportaudit',
            options={'ordering': ['-created_at'], 'permissions': [('export_analytics', 'Puede exportar datos analíticos')], 'verbose_name': 'Auditoría de exportación', 'verbose_name_plural': 'Auditorías de exportación'},
        ),
    ]
