# Generated by Kilo audit implementation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etllog',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etllog',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etllog',
            name='registros_actualizados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etllog',
            name='registros_creados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etllog',
            name='registros_extraidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etllog',
            name='registros_invalidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etllog',
            name='registros_validos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etllog',
            name='schema_version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AddField(
            model_name='etllog',
            name='source_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='etllog',
            name='source_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='etllog',
            name='source_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='etllog',
            name='validation_rules_version',
            field=models.CharField(default='1.0', max_length=20),
        ),
    ]
