# Generated by Django 6.0.6 on 2026-06-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_etllog_audit_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('run_etl', 'Puede ejecutar procesos ETL'), ('upload_etl', 'Puede cargar archivos ETL')]},
        ),
    ]
