# Generated by Django 6.0.6 on 2026-06-16 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_alter_patient_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaTransaccionalETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('archivo_fuente', models.CharField(blank=True, max_length=255, null=True)),
                ('registros_saneados', models.IntegerField(default=0)),
                ('tiempo_ejecucion_segundos', models.FloatField(default=0.0)),
                ('estado_finalizacion', models.CharField(choices=[('EXITOSO', 'EXITOSO'), ('FALLIDO', 'FALLIDO')], default='EXITOSO', max_length=15)),
                ('informe_errores', models.TextField(blank=True, null=True)),
                ('usuario_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_etl', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_procesos_etl',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
    ]
