# Generated by Django 6.0.5 on 2026-05-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(blank=True, default='', max_length=20)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('imc', models.FloatField(blank=True, null=True)),
                ('presion_sistolica', models.IntegerField(blank=True, null=True)),
                ('presion_diastolica', models.IntegerField(blank=True, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('glucosa', models.FloatField(blank=True, null=True)),
                ('colesterol', models.FloatField(blank=True, null=True)),
                ('saturacion_oxigeno', models.FloatField(blank=True, null=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('antecedentes_familiares', models.BooleanField(default=False)),
                ('fumador', models.BooleanField(default=False)),
                ('consumo_alcohol', models.BooleanField(default=False)),
                ('actividad_fisica', models.CharField(blank=True, default='', max_length=100)),
                ('diagnostico_preliminar', models.CharField(blank=True, default='', max_length=255)),
                ('riesgo_enfermedad', models.CharField(blank=True, default='', max_length=20)),
                ('fecha_consulta', models.DateField(blank=True, null=True)),
                ('id_paciente', models.IntegerField(unique=True)),
                ('nombres', models.CharField(blank=True, default='', max_length=100)),
                ('apellidos', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
    ]
