# Generated by Django 6.0.5 on 2026-05-27 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('fuente', models.CharField(blank=True, default='', max_length=255)),
                ('registros_extraccion', models.IntegerField(blank=True, null=True)),
                ('registros_transformados', models.IntegerField(blank=True, null=True)),
                ('tiempo_ejecucion_ms', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etl_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'etl_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ETLLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.CharField(blank=True, default='INFO', max_length=20)),
                ('mensaje', models.TextField()),
                ('etl_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='etl.etlrun')),
            ],
            options={
                'db_table': 'etl_logs',
                'ordering': ['created_at'],
            },
        ),
    ]
