# Generated by Django 6.0.6 on 2026-06-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_patient', 'Puede consultar pacientes del ETL'), ('view_etllog', 'Puede consultar logs del ETL'), ('view_kpi', 'Puede consultar indicadores analíticos'), ('export_analytics', 'Puede exportar datos analíticos')]},
        ),
    ]
