# Generated by Kilo audit implementation

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodelmetrics',
            name='feature_names_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mlmodelmetrics',
            name='label_encoder_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mlmodelmetrics',
            name='model_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mlmodelmetrics',
            name='model_version',
            field=models.CharField(default='random_forest_v1', max_length=100),
        ),
        migrations.CreateModel(
            name='PredictionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=100)),
                ('model_path', models.CharField(max_length=255)),
                ('model_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('input_data', models.JSONField()),
                ('prediction', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de predicción ML',
                'verbose_name_plural': 'Auditorías de predicción ML',
                'ordering': ['-created_at'],
            },
        ),
    ]
