# Generated by Django 6.0.6 on 2026-06-14 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_ml_audit_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlmodelmetrics',
            options={'ordering': ['-trained_at'], 'permissions': [('predict_ml', 'Puede ejecutar predicciones ML')], 'verbose_name': 'Métrica del modelo ML', 'verbose_name_plural': 'Métricas del modelo ML'},
        ),
    ]
